[package]
name = "convergence"
version = "0.1"
lean_version = "leanprover-community/lean:3.45.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "903e8941f0862f6c34f28babbb607842a7f8a6c7"}
