[package]
name = "lean-play"
version = "0.1"
lean_version = "leanprover-community/lean:3.35.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "dd1242d2aec84561c8f8651721ea1c1d8d25007a"}
